version: "3"

volumes:
  shahid_aleali_local_postgres_data: {}
  shahid_aleali_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: shahid_aleali_local_django
    container_name: shahid_aleali_local_django
    depends_on:
      - postgres_shahid_aleali
      - redis
    volumes:
      - .:/app:z
      - ./.vscode-server:/root/.vscode-server/
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8080:8000"
    command: /start
    environment:
      - name=shahid_aleali_local_django
      - VIRTUAL_HOST=shahid-aleali.site,api.shahid-aleali.site
      - LETSENCRYPT_HOST=shahid-aleali.site,api.shahid-aleali.site
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
    network_mode: bridge


  postgres_shahid_aleali:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: shahid_aleali_production_postgres
    container_name: shahid_aleali_local_postgres
    volumes:
      - shahid_aleali_local_postgres_data:/var/lib/postgresql/data
      - shahid_aleali_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: shahid_aleali_local_redis
    network_mode: bridge
    ports:
      - "7979:6379"
