version: "3"

volumes:
  shahid_aleali_local_postgres_data: {}
  shahid_aleali_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: shahid_aleali_local_django
    container_name: shahid_aleali_local_django
    depends_on:
      - postgres_shahid_aleali
      - redis
    volumes:
      - .:/app:z
      - ./.vscode-server:/root/.vscode-server/
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8787:8000"
    command: /start
    environment:
      - name=nginx
      - VIRTUAL_HOST=apiv2.iranzamin.site
      - LETSENCRYPT_HOST=apiv2.iranzamin.site
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true

  postgres_shahid_aleali:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: shahid_aleali_production_postgres
    container_name: shahid_aleali_local_postgres
    volumes:
      - shahid_aleali_local_postgres_data:/var/lib/postgresql/data
      - shahid_aleali_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: shahid_aleali_local_redis

  celeryworker:
    <<: *django
    image: shahid_aleali_local_celeryworker
    container_name: shahid_aleali_local_celeryworker
    depends_on:
      - redis
      - postgres_shahid_aleali
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: shahid_aleali_local_celerybeat
    container_name: shahid_aleali_local_celerybeat
    depends_on:
      - redis
      - postgres_shahid_aleali
    ports: []
    command: /start-celerybeat
